name: 'eslint'
description: 'see https://www.npmjs.com/package/eslint'
runs:
  using: "composite"
  steps:
     - uses: ./foundation/.github/actions/npm-init
     - name: lint webapp
       run: npx eslint webapp
       shell: bash